//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radish.Templates.Bootstrap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radish.Templates.Bootstrap.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;panel panel-default&quot; id=&quot;method-id-{{id}}&quot;&gt;
        ///	
        ///	&lt;div class=&quot;panel-heading&quot; role=&quot;tab&quot; id=&quot;heading-method-{{id}}&quot;&gt;
        ///		&lt;div class=&quot;panel-title&quot;&gt;
        ///			&lt;samp&gt;
        ///				&lt;span class=&quot;label label-method-{{method}}&quot;&gt;{{method}}&lt;/span&gt;
        ///				&lt;span class=&quot;label label-default&quot;&gt;{{route}}&lt;/span&gt;
        ///			&lt;/samp&gt;
        ///			&lt;div class=&quot;pull-right&quot;&gt;
        ///				&lt;a data-toggle=&quot;collapse&quot; data-parent=&quot;#accordion-method&quot; href=&quot;#collapse-method-{{id}}&quot; aria-expanded=&quot;false&quot; aria-controls=&quot;collapse-method-{{id}}&quot;&gt;
        ///					&lt;h3&gt;{{title}}&lt;/h3&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;{{title}}&lt;/h2&gt;
        ///&lt;p&gt;{{description}}&lt;/p&gt;
        ///&lt;br&gt;.
        /// </summary>
        internal static string MethodsGroup {
            get {
                return ResourceManager.GetString("MethodsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///        &lt;meta name=&quot;generator&quot; content=&quot;Radish: https://github.com/alexanderkrutov/radish/&quot;&gt;
        ///	   
        ///		&lt;title&gt;{{title}}&lt;/title&gt;
        ///
        ///		&lt;!-- Bootstrap core CSS --&gt;
        ///		&lt;link href=&quot;https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///		&lt;link href=&quot;https://cdnjs.cloud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Request body description --&gt;
        ///&lt;h4&gt;Request&lt;/h4&gt;
        ///&lt;p&gt;{{description}}&lt;/p&gt;
        ///&lt;br&gt;.
        /// </summary>
        internal static string RequestBodyDescription {
            get {
                return ResourceManager.GetString("RequestBodyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Request body example --&gt;
        ///&lt;h4&gt;Request body example&lt;/h4&gt;
        ///&lt;p&gt;	
        ///    &lt;pre id=&quot;request-example-{{id}}&quot; class=&quot;databox prettyprint&quot;&gt;&lt;/pre&gt;
        ///&lt;/p&gt;
        ///&lt;br&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    highlightExampleCode(&apos;request-example-{{id}}&apos;, &apos;{{data}}&apos;, &apos;{{data-format}}&apos;);
        ///&lt;/script&gt;.
        /// </summary>
        internal static string RequestBodyExample {
            get {
                return ResourceManager.GetString("RequestBodyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///	&lt;td class=&quot;parameter-name&quot;&gt;{{name}}&lt;/td&gt;
        ///	&lt;td&gt;{{type}}&lt;/td&gt;
        ///	&lt;td&gt;{{required}}&lt;/td&gt;
        ///	&lt;td&gt;{{description}}&lt;/td&gt;
        ///&lt;/tr&gt;.
        /// </summary>
        internal static string RequestParameter {
            get {
                return ResourceManager.GetString("RequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Request parameters --&gt;
        ///&lt;h4&gt;Request Parameters&lt;/h4&gt;
        ///&lt;table class=&quot;table table-striped table-bordered table-condensed&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;th&gt;Parameter&lt;/th&gt;
        ///		&lt;th&gt;Type&lt;/th&gt;
        ///		&lt;th&gt;Required&lt;/th&gt;
        ///		&lt;th&gt;Description&lt;/th&gt;
        ///	&lt;/tr&gt;
        ///	{{request-parameters-list}}
        ///&lt;/table&gt;
        ///&lt;br&gt;.
        /// </summary>
        internal static string RequestParametersList {
            get {
                return ResourceManager.GetString("RequestParametersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Response body description --&gt;
        ///&lt;h4&gt;Response&lt;/h4&gt;
        ///&lt;p&gt;{{description}}&lt;/p&gt;
        ///&lt;br&gt;.
        /// </summary>
        internal static string ResponseBodyDescription {
            get {
                return ResourceManager.GetString("ResponseBodyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- Response body example --&gt;
        ///&lt;h4&gt;Response body example&lt;/h4&gt;
        ///&lt;p&gt;	
        ///    &lt;pre id=&quot;response-example-{{id}}&quot; class=&quot;databox prettyprint&quot;&gt;&lt;/pre&gt;
        ///&lt;/p&gt;
        ///&lt;br&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    highlightExampleCode(&apos;response-example-{{id}}&apos;, &apos;{{data}}&apos;, &apos;{{data-format}}&apos;);
        ///&lt;/script&gt;.
        /// </summary>
        internal static string ResponseBodyExample {
            get {
                return ResourceManager.GetString("ResponseBodyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ResponseCode --&gt;
        ///&lt;div class=&quot;alert-response-code-{{code}} alert&quot;&gt;
        ///	&lt;span class=&quot;label-response-code-{{code}} label label-lg&quot;&gt;{{code}}&lt;/span&gt; {{description}}
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ResponseCode {
            get {
                return ResourceManager.GetString("ResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ResponseCodesList --&gt;
        ///&lt;h4&gt;Response codes&lt;/h4&gt;
        ///&lt;p&gt;
        ///{{response-codes-list}}
        ///&lt;/p&gt;.
        /// </summary>
        internal static string ResponseCodesList {
            get {
                return ResourceManager.GetString("ResponseCodesList", resourceCulture);
            }
        }
    }
}
