#region License
//   Copyright (C) 2015 Alexander Krutov
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
#endregion License

using System;
using System.Text.RegularExpressions;
using System.Web;

namespace Radish
{
    /// <summary>
    /// Defines REST API method type and route in the HTML documentation output.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    public sealed class MethodAttribute : RadishAttribute
    {
        /// <summary>
        /// REST API method type (GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS)
        /// </summary>
        public string MethodType { private set; get; }

        /// <summary>
        /// REST API method route, i.e. URL path to execute the method
        /// </summary>
        public string Route { private set; get; }

        /// <summary>
        /// Internal string identifier of the method in HTML documentation. 
        /// Needed for search navigation; also may be used as an HTML anchor like: #identifier.
        /// If Id is not specified, autogenerated GUID string will be used.
        /// </summary>
        public string Id { private set; get; }

        /// <summary>
        /// Defines REST API method type and route in the HTML documentation output.
        /// </summary>
        /// <param name="methodType">REST API method type (GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS).</param>
        /// <param name="methodRoute">REST API method route, i.e. URL path to execute the method</param>
        public MethodAttribute(string methodType, string methodRoute) : this(methodType, methodRoute, Guid.NewGuid().ToString()) { }
        
        /// <summary>
        /// Defines REST API method type, route and method identifier in the HTML documentation output.
        /// </summary>
        /// <param name="methodType">REST API method type (GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS).</param>
        /// <param name="methodRoute">REST API method route, i.e. URL path to execute the method</param>
        /// <param name="id">
        /// Internal string identifier of the method in HTML documentation. 
        /// Needed for search navigation; also may be used as an HTML anchor like: #identifier.
        /// If Id is not specified, autogenerated GUID string will be used.
        /// Method identifier may contain letters, digits, underscore and dash symbols only.
        /// </param>
        public MethodAttribute(string methodType, string methodRoute, string id)
        {
            // check id
            if (!Regex.IsMatch(id, "^[a-zA-Z0-9_-]+$"))
            {
                throw new ArgumentException("Method identifier may contain letters, digits, underscore and dash symbols only.");
            }

            this.MethodType = methodType;
            this.Route = HttpUtility.HtmlEncode(methodRoute);
            this.Id = id;
        }
    }
}
